SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [MERGEPROCESS_New].[PreMerge]
	AS 
Declare @LogDate datetime = (Select getdate())

INSERT INTO MERGEPROCESS_New.LogPreMergeAccount
Select a.FK_MergeID,ObjectType, 'Winner' MergeRecordType, @LogDate LogDate,
b.accountcategorycode,
b.accountcategorycodename,
b.accountclassificationcode,
b.accountclassificationcodename,
b.accountid,
b.accountnumber,
b.accountratingcode,
b.accountratingcodename,
b.address1_addressid,
b.address1_addresstypecode,
b.address1_addresstypecodename,
b.address1_city,
b.address1_composite,
b.address1_country,
b.address1_county,
b.address1_fax,
b.address1_freighttermscode,
b.address1_freighttermscodename,
b.address1_latitude,
b.address1_line1,
b.address1_line2,
b.address1_line3,
b.address1_longitude,
b.address1_name,
b.address1_postalcode,
b.address1_postofficebox,
b.address1_primarycontactname,
b.address1_shippingmethodcode,
b.address1_shippingmethodcodename,
b.address1_stateorprovince,
b.address1_telephone1,
b.address1_telephone2,
b.address1_telephone3,
b.address1_upszone,
b.address1_utcoffset,
b.address2_addressid,
b.address2_addresstypecode,
b.address2_addresstypecodename,
b.address2_city,
b.address2_composite,
b.address2_country,
b.address2_county,
b.address2_fax,
b.address2_freighttermscode,
b.address2_freighttermscodename,
b.address2_latitude,
b.address2_line1,
b.address2_line2,
b.address2_line3,
b.address2_longitude,
b.address2_name,
b.address2_postalcode,
b.address2_postofficebox,
b.address2_primarycontactname,
b.address2_shippingmethodcode,
b.address2_shippingmethodcodename,
b.address2_stateorprovince,
b.address2_telephone1,
b.address2_telephone2,
b.address2_telephone3,
b.address2_upszone,
b.address2_utcoffset,
b.aging30,
b.aging30_base,
b.aging60,
b.aging60_base,
b.aging90,
b.aging90_base,
b.businesstypecode,
b.businesstypecodename,
b.createdby,
b.createdbyname,
b.createdbyyominame,
b.createdon,
b.createdonbehalfby,
b.createdonbehalfbyname,
b.createdonbehalfbyyominame,
b.creditlimit,
b.creditlimit_base,
b.creditonhold,
b.creditonholdname,
b.customersizecode,
b.customersizecodename,
b.customertypecode,
b.customertypecodename,
b.defaultpricelevelid,
b.defaultpricelevelidname,
b.description,
b.donotbulkemail,
b.donotbulkemailname,
b.donotbulkpostalmail,
b.donotbulkpostalmailname,
b.donotemail,
b.donotemailname,
b.donotfax,
b.donotfaxname,
b.donotphone,
b.donotphonename,
b.donotpostalmail,
b.donotpostalmailname,
b.donotsendmarketingmaterialname,
b.donotsendmm,
b.emailaddress1,
b.emailaddress2,
b.emailaddress3,
b.entityimage,
b.entityimage_timestamp,
b.entityimage_url,
b.entityimageid,
b.exchangerate,
b.fax,
b.ftpsiteurl,
b.importsequencenumber,
b.industrycode,
b.industrycodename,
b.isprivatename,
b.lastusedincampaign,
b.marketcap,
b.marketcap_base,
b.masteraccountidname,
b.masteraccountidyominame,
b.masterid,
b.merged,
b.mergedname,
b.modifiedby,
b.modifiedbyname,
b.modifiedbyyominame,
b.modifiedon,
b.modifiedonbehalfby,
b.modifiedonbehalfbyname,
b.modifiedonbehalfbyyominame,
b.name,
b.numberofemployees,
b.opendeals,
b.opendeals_date,
b.opendeals_state,
b.openrevenue,
b.openrevenue_base,
b.openrevenue_date,
b.openrevenue_state,
b.originatingleadid,
b.originatingleadidname,
b.originatingleadidyominame,
b.overriddencreatedon,
b.ownerid,
b.owneridname,
b.owneridtype,
b.owneridyominame,
b.ownershipcode,
b.ownershipcodename,
b.owningbusinessunit,
b.owningteam,
b.owninguser,
b.parentaccountid,
b.parentaccountidname,
b.parentaccountidyominame,
b.participatesinworkflow,
b.participatesinworkflowname,
b.paymenttermscode,
b.paymenttermscodename,
b.preferredappointmentdaycode,
b.preferredappointmentdaycodename,
b.preferredappointmenttimecode,
b.preferredappointmenttimecodename,
b.preferredcontactmethodcode,
b.preferredcontactmethodcodename,
b.preferredequipmentid,
b.preferredequipmentidname,
b.preferredserviceid,
b.preferredserviceidname,
b.preferredsystemuserid,
b.preferredsystemuseridname,
b.preferredsystemuseridyominame,
b.primarycontactid,
b.primarycontactidname,
b.primarycontactidyominame,
b.processid,
b.revenue,
b.revenue_base,
b.sharesoutstanding,
b.shippingmethodcode,
b.shippingmethodcodename,
b.sic,
b.stageid,
b.statecode,
b.statecodename,
b.statuscode,
b.statuscodename,
b.stockexchange,
b.str_category,
b.str_custom1,
b.str_custom2,
b.str_custom3,
b.str_custom4,
b.str_dwduplicate,
b.str_dwduplicatename,
b.str_dwid,
b.str_dwmodifiedon,
b.str_id,
b.str_idtext,
b.str_leadsourcecode,
b.str_leadsourcecodename,
b.str_league1,
b.str_league2,
b.str_league3,
b.str_league4,
b.str_league5,
b.str_league6,
b.str_league7,
b.str_league8,
b.str_marketingaccountindustryid,
b.str_marketingaccountindustryidname,
b.str_marketingaccountsourceid,
b.str_marketingaccountsourceidname,
b.str_number,
b.str_partnersalesperson,
b.str_partnersalespersonname,
b.str_partnersalespersonyominame,
b.str_partnerserviceperson,
b.str_partnerservicepersonname,
b.str_partnerservicepersonyominame,
b.str_partnershipclosedate,
b.str_partnershipcloseprobability,
b.str_partnershipcomments,
b.str_partnershipphase,
b.str_partnershiprevenue,
b.str_partnershiprevenue_base,
b.str_partnershipstatus,
b.str_premiumsalesperson,
b.str_premiumsalespersonname,
b.str_premiumsalespersonyominame,
b.str_premiumserviceperson,
b.str_premiumservicepersonname,
b.str_premiumservicepersonyominame,
b.str_search,
b.str_select,
b.str_selectname,
b.str_serviceperson,
b.str_servicepersonname,
b.str_servicepersonyominame,
b.str_source,
b.telephone1,
b.telephone2,
b.telephone3,
b.territorycode,
b.territorycodename,
b.territoryid,
b.territoryidname,
b.tickersymbol,
b.timezoneruleversionnumber,
b.transactioncurrencyid,
b.transactioncurrencyidname,
b.traversedpath,
b.utcconversiontimezonecode,
b.versionnumber,
b.websiteurl,
b.yominame,
b.copyloaddate,
b.new_ssbcrmsystemssidwinner,
b.new_ssbcrmsystemdimcustomerids,
b.new_ssbcrmsystemacctid
FROM MERGEPROCESS_New.Queue a
JOIN Vikings_Reporting.Prodcopy.Account b (NOLOCK)
	ON a.Winner_ID = b.Accountid
UNION ALL
Select a.FK_MergeID,ObjectType, 'Loser' MergeRecordType, @LogDate LogDate,
b.accountcategorycode,
b.accountcategorycodename,
b.accountclassificationcode,
b.accountclassificationcodename,
b.accountid,
b.accountnumber,
b.accountratingcode,
b.accountratingcodename,
b.address1_addressid,
b.address1_addresstypecode,
b.address1_addresstypecodename,
b.address1_city,
b.address1_composite,
b.address1_country,
b.address1_county,
b.address1_fax,
b.address1_freighttermscode,
b.address1_freighttermscodename,
b.address1_latitude,
b.address1_line1,
b.address1_line2,
b.address1_line3,
b.address1_longitude,
b.address1_name,
b.address1_postalcode,
b.address1_postofficebox,
b.address1_primarycontactname,
b.address1_shippingmethodcode,
b.address1_shippingmethodcodename,
b.address1_stateorprovince,
b.address1_telephone1,
b.address1_telephone2,
b.address1_telephone3,
b.address1_upszone,
b.address1_utcoffset,
b.address2_addressid,
b.address2_addresstypecode,
b.address2_addresstypecodename,
b.address2_city,
b.address2_composite,
b.address2_country,
b.address2_county,
b.address2_fax,
b.address2_freighttermscode,
b.address2_freighttermscodename,
b.address2_latitude,
b.address2_line1,
b.address2_line2,
b.address2_line3,
b.address2_longitude,
b.address2_name,
b.address2_postalcode,
b.address2_postofficebox,
b.address2_primarycontactname,
b.address2_shippingmethodcode,
b.address2_shippingmethodcodename,
b.address2_stateorprovince,
b.address2_telephone1,
b.address2_telephone2,
b.address2_telephone3,
b.address2_upszone,
b.address2_utcoffset,
b.aging30,
b.aging30_base,
b.aging60,
b.aging60_base,
b.aging90,
b.aging90_base,
b.businesstypecode,
b.businesstypecodename,
b.createdby,
b.createdbyname,
b.createdbyyominame,
b.createdon,
b.createdonbehalfby,
b.createdonbehalfbyname,
b.createdonbehalfbyyominame,
b.creditlimit,
b.creditlimit_base,
b.creditonhold,
b.creditonholdname,
b.customersizecode,
b.customersizecodename,
b.customertypecode,
b.customertypecodename,
b.defaultpricelevelid,
b.defaultpricelevelidname,
b.description,
b.donotbulkemail,
b.donotbulkemailname,
b.donotbulkpostalmail,
b.donotbulkpostalmailname,
b.donotemail,
b.donotemailname,
b.donotfax,
b.donotfaxname,
b.donotphone,
b.donotphonename,
b.donotpostalmail,
b.donotpostalmailname,
b.donotsendmarketingmaterialname,
b.donotsendmm,
b.emailaddress1,
b.emailaddress2,
b.emailaddress3,
b.entityimage,
b.entityimage_timestamp,
b.entityimage_url,
b.entityimageid,
b.exchangerate,
b.fax,
b.ftpsiteurl,
b.importsequencenumber,
b.industrycode,
b.industrycodename,
b.isprivatename,
b.lastusedincampaign,
b.marketcap,
b.marketcap_base,
b.masteraccountidname,
b.masteraccountidyominame,
b.masterid,
b.merged,
b.mergedname,
b.modifiedby,
b.modifiedbyname,
b.modifiedbyyominame,
b.modifiedon,
b.modifiedonbehalfby,
b.modifiedonbehalfbyname,
b.modifiedonbehalfbyyominame,
b.name,
b.numberofemployees,
b.opendeals,
b.opendeals_date,
b.opendeals_state,
b.openrevenue,
b.openrevenue_base,
b.openrevenue_date,
b.openrevenue_state,
b.originatingleadid,
b.originatingleadidname,
b.originatingleadidyominame,
b.overriddencreatedon,
b.ownerid,
b.owneridname,
b.owneridtype,
b.owneridyominame,
b.ownershipcode,
b.ownershipcodename,
b.owningbusinessunit,
b.owningteam,
b.owninguser,
b.parentaccountid,
b.parentaccountidname,
b.parentaccountidyominame,
b.participatesinworkflow,
b.participatesinworkflowname,
b.paymenttermscode,
b.paymenttermscodename,
b.preferredappointmentdaycode,
b.preferredappointmentdaycodename,
b.preferredappointmenttimecode,
b.preferredappointmenttimecodename,
b.preferredcontactmethodcode,
b.preferredcontactmethodcodename,
b.preferredequipmentid,
b.preferredequipmentidname,
b.preferredserviceid,
b.preferredserviceidname,
b.preferredsystemuserid,
b.preferredsystemuseridname,
b.preferredsystemuseridyominame,
b.primarycontactid,
b.primarycontactidname,
b.primarycontactidyominame,
b.processid,
b.revenue,
b.revenue_base,
b.sharesoutstanding,
b.shippingmethodcode,
b.shippingmethodcodename,
b.sic,
b.stageid,
b.statecode,
b.statecodename,
b.statuscode,
b.statuscodename,
b.stockexchange,
b.str_category,
b.str_custom1,
b.str_custom2,
b.str_custom3,
b.str_custom4,
b.str_dwduplicate,
b.str_dwduplicatename,
b.str_dwid,
b.str_dwmodifiedon,
b.str_id,
b.str_idtext,
b.str_leadsourcecode,
b.str_leadsourcecodename,
b.str_league1,
b.str_league2,
b.str_league3,
b.str_league4,
b.str_league5,
b.str_league6,
b.str_league7,
b.str_league8,
b.str_marketingaccountindustryid,
b.str_marketingaccountindustryidname,
b.str_marketingaccountsourceid,
b.str_marketingaccountsourceidname,
b.str_number,
b.str_partnersalesperson,
b.str_partnersalespersonname,
b.str_partnersalespersonyominame,
b.str_partnerserviceperson,
b.str_partnerservicepersonname,
b.str_partnerservicepersonyominame,
b.str_partnershipclosedate,
b.str_partnershipcloseprobability,
b.str_partnershipcomments,
b.str_partnershipphase,
b.str_partnershiprevenue,
b.str_partnershiprevenue_base,
b.str_partnershipstatus,
b.str_premiumsalesperson,
b.str_premiumsalespersonname,
b.str_premiumsalespersonyominame,
b.str_premiumserviceperson,
b.str_premiumservicepersonname,
b.str_premiumservicepersonyominame,
b.str_search,
b.str_select,
b.str_selectname,
b.str_serviceperson,
b.str_servicepersonname,
b.str_servicepersonyominame,
b.str_source,
b.telephone1,
b.telephone2,
b.telephone3,
b.territorycode,
b.territorycodename,
b.territoryid,
b.territoryidname,
b.tickersymbol,
b.timezoneruleversionnumber,
b.transactioncurrencyid,
b.transactioncurrencyidname,
b.traversedpath,
b.utcconversiontimezonecode,
b.versionnumber,
b.websiteurl,
b.yominame,
b.copyloaddate,
b.new_ssbcrmsystemssidwinner,
b.new_ssbcrmsystemdimcustomerids,
b.new_ssbcrmsystemacctid
FROM MERGEPROCESS_New.Queue a (NOLOCK)
JOIN Vikings_Reporting.Prodcopy.Account b (NOLOCK)
	ON a.Loser_ID = b.Accountid

INSERT INTO MERGEPROCESS_New.LogPreMergeContact
SELECT a.FK_MergeID, ObjectType, 'Winner' MergeRecordType, @LogDate LogDate,
	[accountid] ,
	[accountidname] ,
	[accountidyominame] ,
	[accountrolecode] ,
	[accountrolecodename] ,
	[address1_addressid] ,
	[address1_addresstypecode] ,
	[address1_addresstypecodename] ,
	[address1_city] ,
	[address1_composite] ,
	[address1_country] ,
	[address1_county] ,
	[address1_fax] ,
	[address1_freighttermscode] ,
	[address1_freighttermscodename] ,
	[address1_latitude] ,
	[address1_line1] ,
	[address1_line2] ,
	[address1_line3] ,
	[address1_longitude] ,
	[address1_name] ,
	[address1_postalcode] ,
	[address1_postofficebox] ,
	[address1_primarycontactname] ,
	[address1_shippingmethodcode] ,
	[address1_shippingmethodcodename] ,
	[address1_stateorprovince] ,
	[address1_telephone1] ,
	[address1_telephone2] ,
	[address1_telephone3] ,
	[address1_upszone] ,
	[address1_utcoffset] ,
	[address2_addressid] ,
	[address2_addresstypecode] ,
	[address2_addresstypecodename] ,
	[address2_city] ,
	[address2_composite] ,
	[address2_country] ,
	[address2_county] ,
	[address2_fax] ,
	[address2_freighttermscode] ,
	[address2_freighttermscodename] ,
	[address2_latitude] ,
	[address2_line1] ,
	[address2_line2] ,
	[address2_line3] ,
	[address2_longitude] ,
	[address2_name] ,
	[address2_postalcode] ,
	[address2_postofficebox] ,
	[address2_primarycontactname] ,
	[address2_shippingmethodcode] ,
	[address2_shippingmethodcodename] ,
	[address2_stateorprovince] ,
	[address2_telephone1] ,
	[address2_telephone2] ,
	[address2_telephone3] ,
	[address2_upszone] ,
	[address2_utcoffset] ,
	[address3_addressid] ,
	[address3_addresstypecode] ,
	[address3_addresstypecodename] ,
	[address3_city] ,
	[address3_composite] ,
	[address3_country] ,
	[address3_county] ,
	[address3_fax] ,
	[address3_freighttermscode] ,
	[address3_freighttermscodename] ,
	[address3_latitude] ,
	[address3_line1] ,
	[address3_line2] ,
	[address3_line3] ,
	[address3_longitude] ,
	[address3_name] ,
	[address3_postalcode] ,
	[address3_postofficebox] ,
	[address3_primarycontactname] ,
	[address3_shippingmethodcode] ,
	[address3_shippingmethodcodename] ,
	[address3_stateorprovince] ,
	[address3_telephone1] ,
	[address3_telephone2] ,
	[address3_telephone3] ,
	[address3_upszone] ,
	[address3_utcoffset] ,
	[aging30] ,
	[aging30_base] ,
	[aging60] ,
	[aging60_base] ,
	[aging90] ,
	[aging90_base] ,
	[anniversary] ,
	[annualincome] ,
	[annualincome_base] ,
	[assistantname] ,
	[assistantphone] ,
	[birthdate] ,
	[business2] ,
	[callback] ,
	[childrensnames] ,
	[company] ,
	[contactid] ,
	[createdby] ,
	[createdbyexternalparty] ,
	[createdbyexternalpartyname] ,
	[createdbyexternalpartyyominame] ,
	[createdbyname] ,
	[createdbyyominame] ,
	[createdon] ,
	[createdonbehalfby] ,
	[createdonbehalfbyname] ,
	[createdonbehalfbyyominame] ,
	[creditlimit] ,
	[creditlimit_base] ,
	[creditonhold] ,
	[creditonholdname] ,
	[customersizecode] ,
	[customersizecodename] ,
	[customertypecode] ,
	[customertypecodename] ,
	[defaultpricelevelid] ,
	[defaultpricelevelidname] ,
	[department] ,
	[description] ,
	[donotbulkemail] ,
	[donotbulkemailname] ,
	[donotbulkpostalmail] ,
	[donotbulkpostalmailname] ,
	[donotemail] ,
	[donotemailname] ,
	[donotfax] ,
	[donotfaxname] ,
	[donotphone] ,
	[donotphonename] ,
	[donotpostalmail] ,
	[donotpostalmailname] ,
	[donotsendmarketingmaterialname] ,
	[donotsendmm] ,
	[educationcode] ,
	[educationcodename] ,
	[emailaddress1] ,
	[emailaddress2] ,
	[emailaddress3] ,
	[employeeid] ,
	[entityimage] ,
	[entityimage_timestamp] ,
	[entityimage_url] ,
	[entityimageid] ,
	[exchangerate] ,
	[externaluseridentifier] ,
	[familystatuscode] ,
	[familystatuscodename] ,
	[fax] ,
	[firstname] ,
	[ftpsiteurl] ,
	[fullname] ,
	[gendercode] ,
	[gendercodename] ,
	[governmentid] ,
	[haschildrencode] ,
	[haschildrencodename] ,
	[home2] ,
	[importsequencenumber] ,
	[isbackofficecustomer] ,
	[isbackofficecustomername] ,
	[isprivatename] ,
	[jobtitle] ,
	[lastname] ,
	[lastonholdtime] ,
	[lastusedincampaign] ,
	[leadsourcecode] ,
	[leadsourcecodename] ,
	[managername] ,
	[managerphone] ,
	[mastercontactidname] ,
	[mastercontactidyominame] ,
	[masterid] ,
	[merged] ,
	[mergedname] ,
	[middlename] ,
	[mobilephone] ,
	[modifiedby] ,
	[modifiedbyexternalparty] ,
	[modifiedbyexternalpartyname] ,
	[modifiedbyexternalpartyyominame] ,
	[modifiedbyname] ,
	[modifiedbyyominame] ,
	[modifiedon] ,
	[modifiedonbehalfby] ,
	[modifiedonbehalfbyname] ,
	[modifiedonbehalfbyyominame] ,
	[new_eml_partner] ,
	[new_eml_partnername] ,
	[new_invite_clubgift] ,
	[new_invite_clubgiftname] ,
	[new_invite_holidaycard] ,
	[new_invite_holidaycardname] ,
	[new_invite_holidaygift] ,
	[new_invite_holidaygiftname] ,
	[new_invite_presale] ,
	[new_invite_presalename] ,
	[new_invite_seasonendgift] ,
	[new_invite_seasonendgiftname] ,
	[new_invite_suitegift] ,
	[new_invite_suitegiftname] ,
	[new_invite_travel] ,
	[new_invite_travelname] ,
	[new_invite_vip] ,
	[new_invite_vipname] ,
	[new_invite_vvip] ,
	[new_invite_vvipname] ,
	[new_legacycontactid] ,
	[new_manager_club] ,
	[new_manager_clubname] ,
	[new_manager_event] ,
	[new_manager_eventname] ,
	[new_manager_suites] ,
	[new_manager_suitesname] ,
	[new_manager_suitetickets] ,
	[new_manager_suiteticketsname] ,
	[new_manager_tickets] ,
	[new_manager_ticketsname] ,
	[new_ssbcrmsystemacctid] ,
	[new_ssbcrmsystemarchticsids] ,
	[new_ssbcrmsystemcontactid] ,
	[new_ssbcrmsystemdimcustomerids] ,
	[new_ssbcrmsystemssidwinner] ,
	[nickname] ,
	[numberofchildren] ,
	[onholdtime] ,
	[originatingleadid] ,
	[originatingleadidname] ,
	[originatingleadidyominame] ,
	[overriddencreatedon] ,
	[ownerid] ,
	[owneridname] ,
	[owneridtype] ,
	[owneridyominame] ,
	[owningbusinessunit] ,
	[owningteam] ,
	[owninguser] ,
	[pager] ,
	[parentcontactid] ,
	[parentcontactidname] ,
	[parentcontactidyominame] ,
	[parentcustomerid] ,
	[parentcustomeridname] ,
	[parentcustomeridtype] ,
	[parentcustomeridyominame] ,
	[participatesinworkflow] ,
	[participatesinworkflowname] ,
	[paymenttermscode] ,
	[paymenttermscodename] ,
	[preferredappointmentdaycode] ,
	[preferredappointmentdaycodename] ,
	[preferredappointmenttimecode] ,
	[preferredappointmenttimecodename] ,
	[preferredcontactmethodcode] ,
	[preferredcontactmethodcodename] ,
	[preferredequipmentid] ,
	[preferredequipmentidname] ,
	[preferredserviceid] ,
	[preferredserviceidname] ,
	[preferredsystemuserid] ,
	[preferredsystemuseridname] ,
	[preferredsystemuseridyominame] ,
	[processid] ,
	[salutation] ,
	[shippingmethodcode] ,
	[shippingmethodcodename] ,
	[slaid] ,
	[slainvokedid] ,
	[slainvokedidname] ,
	[slaname] ,
	[spousesname] ,
	[stageid] ,
	[statecode] ,
	[statecodename] ,
	[statuscode] ,
	[statuscodename] ,
	[str_agerange] ,
	[str_category] ,
	[str_college] ,
	[str_concertinterests] ,
	[str_datawarehouseid] ,
	[str_externalcapacitymodel] ,
	[str_externalclustername] ,
	[str_externalprioritymodel] ,
	[str_favoritedestination] ,
	[str_favoriteplayer] ,
	[str_favoriterestaurant] ,
	[str_favoriteteam] ,
	[str_hobbies] ,
	[str_hometown] ,
	[str_householdincome] ,
	[str_householdincome_base] ,
	[str_id] ,
	[str_idtext] ,
	[str_lastactivitydate] ,
	[str_marketingcontactsourceid] ,
	[str_marketingcontactsourceidname] ,
	[str_marketingcontacttypeid] ,
	[str_marketingcontacttypeidname] ,
	[str_musicclassical] ,
	[str_musicclassicalname] ,
	[str_musiccountry] ,
	[str_musiccountryname] ,
	[str_musicpop] ,
	[str_musicpopname] ,
	[str_musicrap] ,
	[str_musicrapname] ,
	[str_musicrock] ,
	[str_musicrockname] ,
	[str_neglectmeter] ,
	[str_nextactivitydate] ,
	[str_nextactivitysubject] ,
	[str_number] ,
	[str_openactivitycount] ,
	[str_openticketcase] ,
	[str_openticketcasename] ,
	[str_openticketopportunity] ,
	[str_openticketopportunityname] ,
	[str_oppdaysinstage] ,
	[str_oppproduct] ,
	[str_oppsource] ,
	[str_oppstage] ,
	[str_otherinformation] ,
	[str_partnerid] ,
	[str_partneridname] ,
	[str_partneridyominame] ,
	[str_premiumtype] ,
	[str_premiumtypename] ,
	[str_priority] ,
	[str_rating] ,
	[str_ratingname] ,
	[str_score] ,
	[str_search] ,
	[str_select] ,
	[str_selectname] ,
	[str_serviceperson] ,
	[str_servicepersonname] ,
	[str_servicepersonyominame] ,
	[str_showsfamily] ,
	[str_showsfamilyname] ,
	[str_since] ,
	[str_source] ,
	[str_sportsinterests] ,
	[str_test] ,
	[str_test_date] ,
	[str_test_state] ,
	[str_ticketeventtotalall] ,
	[str_ticketeventtotalarena] ,
	[str_ticketeventtotallast] ,
	[str_ticketeventtotalthis] ,
	[str_ticketnumberaverageall] ,
	[str_ticketnumberaveragearena] ,
	[str_ticketnumberaveragelast] ,
	[str_ticketnumberaveragethis] ,
	[str_ticketnumbertotalall] ,
	[str_ticketnumbertotalarena] ,
	[str_ticketnumbertotallast] ,
	[str_ticketnumbertotalthis] ,
	[str_ticketpriceaverageall] ,
	[str_ticketpriceaverageall_base] ,
	[str_ticketpriceaveragearena] ,
	[str_ticketpriceaveragearena_base] ,
	[str_ticketpriceaveragelast] ,
	[str_ticketpriceaveragelast_base] ,
	[str_ticketpriceaveragethis] ,
	[str_ticketpriceaveragethis_base] ,
	[str_ticketspendaverageall] ,
	[str_ticketspendaverageall_base] ,
	[str_ticketspendaveragearena] ,
	[str_ticketspendaveragearena_base] ,
	[str_ticketspendaveragelast] ,
	[str_ticketspendaveragelast_base] ,
	[str_ticketspendaveragethis] ,
	[str_ticketspendaveragethis_base] ,
	[str_ticketspendtotalall] ,
	[str_ticketspendtotalall_base] ,
	[str_ticketspendtotalarena] ,
	[str_ticketspendtotalarena_base] ,
	[str_ticketspendtotallast] ,
	[str_ticketspendtotallast_base] ,
	[str_ticketspendtotalthis] ,
	[str_ticketspendtotalthis_base] ,
	[suffix] ,
	[telephone1] ,
	[telephone2] ,
	[telephone3] ,
	[territorycode] ,
	[territorycodename] ,
	[timezoneruleversionnumber] ,
	[transactioncurrencyid] ,
	[transactioncurrencyidname] ,
	[traversedpath] ,
	[utcconversiontimezonecode] ,
	[versionnumber] ,
	[websiteurl] ,
	[yomifirstname] ,
	[yomifullname] ,
	[yomilastname] ,
	[yomimiddlename] ,
	[copyloaddate]
FROM MERGEPROCESS_New.Queue a (NOLOCK)
JOIN Vikings_Reporting.Prodcopy.Contact b (NOLOCK)
	ON a.Winner_ID = b.contactid
UNION ALL
SELECT a.FK_MergeID,ObjectType, 'Loser' MergeRecordType, @LogDate LogDate,
[accountid] ,
	[accountidname] ,
	[accountidyominame] ,
	[accountrolecode] ,
	[accountrolecodename] ,
	[address1_addressid] ,
	[address1_addresstypecode] ,
	[address1_addresstypecodename] ,
	[address1_city] ,
	[address1_composite] ,
	[address1_country] ,
	[address1_county] ,
	[address1_fax] ,
	[address1_freighttermscode] ,
	[address1_freighttermscodename] ,
	[address1_latitude] ,
	[address1_line1] ,
	[address1_line2] ,
	[address1_line3] ,
	[address1_longitude] ,
	[address1_name] ,
	[address1_postalcode] ,
	[address1_postofficebox] ,
	[address1_primarycontactname] ,
	[address1_shippingmethodcode] ,
	[address1_shippingmethodcodename] ,
	[address1_stateorprovince] ,
	[address1_telephone1] ,
	[address1_telephone2] ,
	[address1_telephone3] ,
	[address1_upszone] ,
	[address1_utcoffset] ,
	[address2_addressid] ,
	[address2_addresstypecode] ,
	[address2_addresstypecodename] ,
	[address2_city] ,
	[address2_composite] ,
	[address2_country] ,
	[address2_county] ,
	[address2_fax] ,
	[address2_freighttermscode] ,
	[address2_freighttermscodename] ,
	[address2_latitude] ,
	[address2_line1] ,
	[address2_line2] ,
	[address2_line3] ,
	[address2_longitude] ,
	[address2_name] ,
	[address2_postalcode] ,
	[address2_postofficebox] ,
	[address2_primarycontactname] ,
	[address2_shippingmethodcode] ,
	[address2_shippingmethodcodename] ,
	[address2_stateorprovince] ,
	[address2_telephone1] ,
	[address2_telephone2] ,
	[address2_telephone3] ,
	[address2_upszone] ,
	[address2_utcoffset] ,
	[address3_addressid] ,
	[address3_addresstypecode] ,
	[address3_addresstypecodename] ,
	[address3_city] ,
	[address3_composite] ,
	[address3_country] ,
	[address3_county] ,
	[address3_fax] ,
	[address3_freighttermscode] ,
	[address3_freighttermscodename] ,
	[address3_latitude] ,
	[address3_line1] ,
	[address3_line2] ,
	[address3_line3] ,
	[address3_longitude] ,
	[address3_name] ,
	[address3_postalcode] ,
	[address3_postofficebox] ,
	[address3_primarycontactname] ,
	[address3_shippingmethodcode] ,
	[address3_shippingmethodcodename] ,
	[address3_stateorprovince] ,
	[address3_telephone1] ,
	[address3_telephone2] ,
	[address3_telephone3] ,
	[address3_upszone] ,
	[address3_utcoffset] ,
	[aging30] ,
	[aging30_base] ,
	[aging60] ,
	[aging60_base] ,
	[aging90] ,
	[aging90_base] ,
	[anniversary] ,
	[annualincome] ,
	[annualincome_base] ,
	[assistantname] ,
	[assistantphone] ,
	[birthdate] ,
	[business2] ,
	[callback] ,
	[childrensnames] ,
	[company] ,
	[contactid] ,
	[createdby] ,
	[createdbyexternalparty] ,
	[createdbyexternalpartyname] ,
	[createdbyexternalpartyyominame] ,
	[createdbyname] ,
	[createdbyyominame] ,
	[createdon] ,
	[createdonbehalfby] ,
	[createdonbehalfbyname] ,
	[createdonbehalfbyyominame] ,
	[creditlimit] ,
	[creditlimit_base] ,
	[creditonhold] ,
	[creditonholdname] ,
	[customersizecode] ,
	[customersizecodename] ,
	[customertypecode] ,
	[customertypecodename] ,
	[defaultpricelevelid] ,
	[defaultpricelevelidname] ,
	[department] ,
	[description] ,
	[donotbulkemail] ,
	[donotbulkemailname] ,
	[donotbulkpostalmail] ,
	[donotbulkpostalmailname] ,
	[donotemail] ,
	[donotemailname] ,
	[donotfax] ,
	[donotfaxname] ,
	[donotphone] ,
	[donotphonename] ,
	[donotpostalmail] ,
	[donotpostalmailname] ,
	[donotsendmarketingmaterialname] ,
	[donotsendmm] ,
	[educationcode] ,
	[educationcodename] ,
	[emailaddress1] ,
	[emailaddress2] ,
	[emailaddress3] ,
	[employeeid] ,
	[entityimage] ,
	[entityimage_timestamp] ,
	[entityimage_url] ,
	[entityimageid] ,
	[exchangerate] ,
	[externaluseridentifier] ,
	[familystatuscode] ,
	[familystatuscodename] ,
	[fax] ,
	[firstname] ,
	[ftpsiteurl] ,
	[fullname] ,
	[gendercode] ,
	[gendercodename] ,
	[governmentid] ,
	[haschildrencode] ,
	[haschildrencodename] ,
	[home2] ,
	[importsequencenumber] ,
	[isbackofficecustomer] ,
	[isbackofficecustomername] ,
	[isprivatename] ,
	[jobtitle] ,
	[lastname] ,
	[lastonholdtime] ,
	[lastusedincampaign] ,
	[leadsourcecode] ,
	[leadsourcecodename] ,
	[managername] ,
	[managerphone] ,
	[mastercontactidname] ,
	[mastercontactidyominame] ,
	[masterid] ,
	[merged] ,
	[mergedname] ,
	[middlename] ,
	[mobilephone] ,
	[modifiedby] ,
	[modifiedbyexternalparty] ,
	[modifiedbyexternalpartyname] ,
	[modifiedbyexternalpartyyominame] ,
	[modifiedbyname] ,
	[modifiedbyyominame] ,
	[modifiedon] ,
	[modifiedonbehalfby] ,
	[modifiedonbehalfbyname] ,
	[modifiedonbehalfbyyominame] ,
	[new_eml_partner] ,
	[new_eml_partnername] ,
	[new_invite_clubgift] ,
	[new_invite_clubgiftname] ,
	[new_invite_holidaycard] ,
	[new_invite_holidaycardname] ,
	[new_invite_holidaygift] ,
	[new_invite_holidaygiftname] ,
	[new_invite_presale] ,
	[new_invite_presalename] ,
	[new_invite_seasonendgift] ,
	[new_invite_seasonendgiftname] ,
	[new_invite_suitegift] ,
	[new_invite_suitegiftname] ,
	[new_invite_travel] ,
	[new_invite_travelname] ,
	[new_invite_vip] ,
	[new_invite_vipname] ,
	[new_invite_vvip] ,
	[new_invite_vvipname] ,
	[new_legacycontactid] ,
	[new_manager_club] ,
	[new_manager_clubname] ,
	[new_manager_event] ,
	[new_manager_eventname] ,
	[new_manager_suites] ,
	[new_manager_suitesname] ,
	[new_manager_suitetickets] ,
	[new_manager_suiteticketsname] ,
	[new_manager_tickets] ,
	[new_manager_ticketsname] ,
	[new_ssbcrmsystemacctid] ,
	[new_ssbcrmsystemarchticsids] ,
	[new_ssbcrmsystemcontactid] ,
	[new_ssbcrmsystemdimcustomerids] ,
	[new_ssbcrmsystemssidwinner] ,
	[nickname] ,
	[numberofchildren] ,
	[onholdtime] ,
	[originatingleadid] ,
	[originatingleadidname] ,
	[originatingleadidyominame] ,
	[overriddencreatedon] ,
	[ownerid] ,
	[owneridname] ,
	[owneridtype] ,
	[owneridyominame] ,
	[owningbusinessunit] ,
	[owningteam] ,
	[owninguser] ,
	[pager] ,
	[parentcontactid] ,
	[parentcontactidname] ,
	[parentcontactidyominame] ,
	[parentcustomerid] ,
	[parentcustomeridname] ,
	[parentcustomeridtype] ,
	[parentcustomeridyominame] ,
	[participatesinworkflow] ,
	[participatesinworkflowname] ,
	[paymenttermscode] ,
	[paymenttermscodename] ,
	[preferredappointmentdaycode] ,
	[preferredappointmentdaycodename] ,
	[preferredappointmenttimecode] ,
	[preferredappointmenttimecodename] ,
	[preferredcontactmethodcode] ,
	[preferredcontactmethodcodename] ,
	[preferredequipmentid] ,
	[preferredequipmentidname] ,
	[preferredserviceid] ,
	[preferredserviceidname] ,
	[preferredsystemuserid] ,
	[preferredsystemuseridname] ,
	[preferredsystemuseridyominame] ,
	[processid] ,
	[salutation] ,
	[shippingmethodcode] ,
	[shippingmethodcodename] ,
	[slaid] ,
	[slainvokedid] ,
	[slainvokedidname] ,
	[slaname] ,
	[spousesname] ,
	[stageid] ,
	[statecode] ,
	[statecodename] ,
	[statuscode] ,
	[statuscodename] ,
	[str_agerange] ,
	[str_category] ,
	[str_college] ,
	[str_concertinterests] ,
	[str_datawarehouseid] ,
	[str_externalcapacitymodel] ,
	[str_externalclustername] ,
	[str_externalprioritymodel] ,
	[str_favoritedestination] ,
	[str_favoriteplayer] ,
	[str_favoriterestaurant] ,
	[str_favoriteteam] ,
	[str_hobbies] ,
	[str_hometown] ,
	[str_householdincome] ,
	[str_householdincome_base] ,
	[str_id] ,
	[str_idtext] ,
	[str_lastactivitydate] ,
	[str_marketingcontactsourceid] ,
	[str_marketingcontactsourceidname] ,
	[str_marketingcontacttypeid] ,
	[str_marketingcontacttypeidname] ,
	[str_musicclassical] ,
	[str_musicclassicalname] ,
	[str_musiccountry] ,
	[str_musiccountryname] ,
	[str_musicpop] ,
	[str_musicpopname] ,
	[str_musicrap] ,
	[str_musicrapname] ,
	[str_musicrock] ,
	[str_musicrockname] ,
	[str_neglectmeter] ,
	[str_nextactivitydate] ,
	[str_nextactivitysubject] ,
	[str_number] ,
	[str_openactivitycount] ,
	[str_openticketcase] ,
	[str_openticketcasename] ,
	[str_openticketopportunity] ,
	[str_openticketopportunityname] ,
	[str_oppdaysinstage] ,
	[str_oppproduct] ,
	[str_oppsource] ,
	[str_oppstage] ,
	[str_otherinformation] ,
	[str_partnerid] ,
	[str_partneridname] ,
	[str_partneridyominame] ,
	[str_premiumtype] ,
	[str_premiumtypename] ,
	[str_priority] ,
	[str_rating] ,
	[str_ratingname] ,
	[str_score] ,
	[str_search] ,
	[str_select] ,
	[str_selectname] ,
	[str_serviceperson] ,
	[str_servicepersonname] ,
	[str_servicepersonyominame] ,
	[str_showsfamily] ,
	[str_showsfamilyname] ,
	[str_since] ,
	[str_source] ,
	[str_sportsinterests] ,
	[str_test] ,
	[str_test_date] ,
	[str_test_state] ,
	[str_ticketeventtotalall] ,
	[str_ticketeventtotalarena] ,
	[str_ticketeventtotallast] ,
	[str_ticketeventtotalthis] ,
	[str_ticketnumberaverageall] ,
	[str_ticketnumberaveragearena] ,
	[str_ticketnumberaveragelast] ,
	[str_ticketnumberaveragethis] ,
	[str_ticketnumbertotalall] ,
	[str_ticketnumbertotalarena] ,
	[str_ticketnumbertotallast] ,
	[str_ticketnumbertotalthis] ,
	[str_ticketpriceaverageall] ,
	[str_ticketpriceaverageall_base] ,
	[str_ticketpriceaveragearena] ,
	[str_ticketpriceaveragearena_base] ,
	[str_ticketpriceaveragelast] ,
	[str_ticketpriceaveragelast_base] ,
	[str_ticketpriceaveragethis] ,
	[str_ticketpriceaveragethis_base] ,
	[str_ticketspendaverageall] ,
	[str_ticketspendaverageall_base] ,
	[str_ticketspendaveragearena] ,
	[str_ticketspendaveragearena_base] ,
	[str_ticketspendaveragelast] ,
	[str_ticketspendaveragelast_base] ,
	[str_ticketspendaveragethis] ,
	[str_ticketspendaveragethis_base] ,
	[str_ticketspendtotalall] ,
	[str_ticketspendtotalall_base] ,
	[str_ticketspendtotalarena] ,
	[str_ticketspendtotalarena_base] ,
	[str_ticketspendtotallast] ,
	[str_ticketspendtotallast_base] ,
	[str_ticketspendtotalthis] ,
	[str_ticketspendtotalthis_base] ,
	[suffix] ,
	[telephone1] ,
	[telephone2] ,
	[telephone3] ,
	[territorycode] ,
	[territorycodename] ,
	[timezoneruleversionnumber] ,
	[transactioncurrencyid] ,
	[transactioncurrencyidname] ,
	[traversedpath] ,
	[utcconversiontimezonecode] ,
	[versionnumber] ,
	[websiteurl] ,
	[yomifirstname] ,
	[yomifullname] ,
	[yomilastname] ,
	[yomimiddlename] ,
	[copyloaddate]
FROM MERGEPROCESS_New.Queue a (NOLOCK)
JOIN Vikings_Reporting.Prodcopy.Contact b (NOLOCK)
	ON a.Loser_ID = b.contactid

GO
